"""Shared enums for the cognitive layer — must match JSON Schema values exactly."""

from enum import StrEnum


class InterpretationMode(StrEnum):
    SINGLE = "SINGLE"
    MULTI_INDEPENDENT = "MULTI_INDEPENDENT"
    MULTI_DEPENDENT = "MULTI_DEPENDENT"
    CLARIFICATION = "CLARIFICATION"
    UNSUPPORTED = "UNSUPPORTED"
    MIXED = "MIXED"


class SelectedRoute(StrEnum):
    BUSINESS_RAG = "BUSINESS_RAG"
    PORTFOLIO_QUERY = "PORTFOLIO_QUERY"
    PERSONAL_READ = "PERSONAL_READ"
    TRANSFER_CONTRACT_BUILDER = "TRANSFER_CONTRACT_BUILDER"
    CLARIFICATION = "CLARIFICATION"
    UNSUPPORTED = "UNSUPPORTED"


class InteractionFamily(StrEnum):
    KNOWLEDGE = "KNOWLEDGE"
    PORTFOLIO = "PORTFOLIO"
    PERSONAL_READ = "PERSONAL_READ"
    TRANSACTION = "TRANSACTION"
    CLARIFICATION = "CLARIFICATION"
    UNSUPPORTED = "UNSUPPORTED"


class NextAction(StrEnum):
    QUERY_RAG = "QUERY_RAG"
    QUERY_PORTFOLIO = "QUERY_PORTFOLIO"
    BUILD_READ_REQUEST = "BUILD_READ_REQUEST"
    BUILD_TYPED_CONTRACT = "BUILD_TYPED_CONTRACT"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    RETURN_UNSUPPORTED = "RETURN_UNSUPPORTED"


class SessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    EXPIRED = "EXPIRED"


class OperationalState(StrEnum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    DORMANT = "DORMANT"


class FreshnessState(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    REFRESHING = "REFRESHING"
    UNAVAILABLE = "UNAVAILABLE"


class SupportLevel(StrEnum):
    INFORMATION_ONLY = "INFORMATION_ONLY"
    GUIDED = "GUIDED"
    ASSISTED = "ASSISTED"
    VALIDATABLE = "VALIDATABLE"
    EXECUTABLE = "EXECUTABLE"


class LifecycleStatus(StrEnum):
    EXPERIMENTAL = "EXPERIMENTAL"
    PILOT = "PILOT"
    PRODUCTION = "PRODUCTION"


class TurnRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
